#!/usr/bin/env bash

dunstctl set-paused true

PICTURE=/tmp/i3lock.png
SCREENSHOT="maim $PICTURE"
BLUR="4x2"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE
i3lock -i $PICTURE  --verif-text=""
rm $PICTURE

dunstctl set-paused false
